"use strict";
(function () {
    'use strict';
    // Do NOT edit this file
    angular
        .module('smartcloudserviceApp')
        .constant('APP_NAME', 'rpc-web-center')
        .constant('VERSION', '1.0.0.RELEASE')
        .constant('COMPANY_NAME', 'Infinity Organization')
        .constant('PAGINATION_CONSTANTS', {
            'itemsPerPage': 10
        })
        //        .constant('ENV', 'test')
        .constant('DEBUG_INFO_ENABLED', true);
})();