"use strict";
(function () {
    'use strict';
    // Do NOT edit this file
    angular
        .module('smartcloudserviceApp')
        .constant('APP_NAME', 'luix-demo-client')
        .constant('PAGINATION_CONSTANTS', {
            'itemsPerPage': 10
         })
        .constant('DEBUG_INFO_ENABLED', true);
})();